# Generated by Django 3.2.25 on 2024-11-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='is_acticae',
            new_name='is_active',
        ),
    ]
